webtalk_init -webtalk_dir C:\\Projects\\FinalProject\\Working\\OrganNotes\\OrganNotes.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2021-03-27 21:27:00" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "q9b2s6f03fsfs8bndm9hdec4ei" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2419 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.640 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1616896663506" -context "sdk\\\\hardware/1616896663506"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1616896663506"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1616896663506"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1616896663506"
webtalk_add_data -client sdk -key VivadoVersion -value "2019.1" -context "sdk\\\\hardware/1616896663506"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1616896663506"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1616896663506"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1616896663506"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1616896663506"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1616896663506"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1616896663506"
webtalk_add_data -client sdk -key uid -value "1616896693183" -context "sdk\\\\bsp/1616896693183"
webtalk_add_data -client sdk -key hwid -value "1616896663506" -context "sdk\\\\bsp/1616896693183"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1616896693183"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1616896693183"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1616896693183"
webtalk_add_data -client sdk -key uid -value "1616896694269" -context "sdk\\\\application/1616896694269"
webtalk_add_data -client sdk -key hwid -value "1616896663506" -context "sdk\\\\application/1616896694269"
webtalk_add_data -client sdk -key bspid -value "1616896693183" -context "sdk\\\\application/1616896694269"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1616896694269"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1616896694269"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1616896694269"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1616896694269"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1616896694269"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1616896694269"
webtalk_add_data -client sdk -key projSize -value "482.80859375" -context "sdk\\\\application/1616896694269"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1616905620864"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1616905620864"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1616905620864"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1616905620864"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1616905620864"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1616905620864"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1616905620864"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1616905620864"
webtalk_transmit -clientid 99904366 -regid "" -xml C:\\Projects\\FinalProject\\Working\\OrganNotes\\OrganNotes.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Projects\\FinalProject\\Working\\OrganNotes\\OrganNotes.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Projects\\FinalProject\\Working\\OrganNotes\\OrganNotes.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
