# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Documents/Zybo-Z7-Master.xdc

# Block Designs: bd/test/test.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test || ORIG_REF_NAME==test} -quiet] -quiet

# IP: bd/test/ip/test_axi_gpio_0_1/test_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_axi_gpio_0_1 || ORIG_REF_NAME==test_axi_gpio_0_1} -quiet] -quiet

# IP: bd/test/ip/test_zybo_audio_ctrl_0_0/test_zybo_audio_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_zybo_audio_ctrl_0_0 || ORIG_REF_NAME==test_zybo_audio_ctrl_0_0} -quiet] -quiet

# IP: bd/test/ip/test_axi_timer_0_0/test_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_axi_timer_0_0 || ORIG_REF_NAME==test_axi_timer_0_0} -quiet] -quiet

# IP: bd/test/ip/test_xlconcat_0_0/test_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_xlconcat_0_0 || ORIG_REF_NAME==test_xlconcat_0_0} -quiet] -quiet

# IP: bd/test/ip/test_axi_gpio_0_3/test_axi_gpio_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_axi_gpio_0_3 || ORIG_REF_NAME==test_axi_gpio_0_3} -quiet] -quiet

# IP: bd/test/ip/test_axi_gpio_0_4/test_axi_gpio_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_axi_gpio_0_4 || ORIG_REF_NAME==test_axi_gpio_0_4} -quiet] -quiet

# IP: bd/test/ip/test_axi_gpio_1_0/test_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_axi_gpio_1_0 || ORIG_REF_NAME==test_axi_gpio_1_0} -quiet] -quiet

# IP: bd/test/ip/test_processing_system7_0_0/test_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_processing_system7_0_0 || ORIG_REF_NAME==test_processing_system7_0_0} -quiet] -quiet

# IP: bd/test/ip/test_xbar_0/test_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_xbar_0 || ORIG_REF_NAME==test_xbar_0} -quiet] -quiet

# IP: bd/test/ip/test_ps7_0_axi_periph_0/test_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_ps7_0_axi_periph_0 || ORIG_REF_NAME==test_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/test/ip/test_rst_ps7_0_50M_0/test_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_rst_ps7_0_50M_0 || ORIG_REF_NAME==test_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/test/ip/test_OrganHarmonizer_0_0/test_OrganHarmonizer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_OrganHarmonizer_0_0 || ORIG_REF_NAME==test_OrganHarmonizer_0_0} -quiet] -quiet

# IP: bd/test/ip/test_auto_pc_0/test_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_auto_pc_0 || ORIG_REF_NAME==test_auto_pc_0} -quiet] -quiet

# XDC: bd/test/test_ooc.xdc
